name: Release

on:
  workflow_run:
    workflows: ["Python package"]
    types: 
      - completed
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'release'}}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build package
      run: |
        python -m pip install --upgrade build
        python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{secrets.PYPI_API_KEY}}
      run: |
        python -m pip install --upgrade twine
        python3 -m twine upload --repository testpypi dist/*
